sudo: required
language: java

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
  - docker build -t u6kapps/rundeck .

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin;
      docker tag u6kapps/rundeck u6kapps/rundeck:$TRAVIS_TAG;
      docker push u6kapps/rundeck;
    else
      echo skip docker push;
    fi

notifications:
  slack:
    secure: kJ/J4vFOEtDtmeJFsQcSaUY1AIKpH+vqEDEoTzFv0mgnAHPb9Lc9mZtq91bk5jaIZV7HxFnNbmlNS8kf9uWA41nH4S4o9LQ4uUhosV0DPIOpb69NquwlAG66X+TNASSroYWhJlfP9Z2PLEg3f++6p5RrXWipNsgC4lqvcR1gtzEIc75rFGnBTYicdLUZ5M41zRcOVv4746a6pepuNZYanVSG5ff1bboYZW+JivLzBn8JhVhAuRq/ssN8YEglEGu7/N7NK9kS338vMzhKMzXzJlUXVp85ES7AP/q/kC3td5hUWbksFn7XYa56MbQNk85uE1PeMMZJUwXeILqrVeNpAOVSkWLOnkHBexYqWsWpaM5lBHjIl1zB/vqmpP6M4Ezsruc620iEPa+00s2lolvnHF7snS/sfyjW1T2pGDBiH5kTpfoR5BaxnqwdGjEDB0mG6TiTHRl82cfgXCVosgmCSt+Lw7T1Z5C/QWcpCS21b1Zcbo8U3h5EsvlHgRs/tCv9AHgrU63FAO1JdYUWDvT3oc4NPS8knI0JYaYu5K7bMHYKC+BdxTmJcrqemk9sfKx1D00GqtLikGkNhnd/L8IAViJ8au9vLO+f3/B3hVOOelQ10np/SQmojYZ+MA3lJ2keYbuVWYrF8w034D5mBQFz3NEXZzPddH7cG62moZOBrqM=
