version: '3'

services:
  rundeck:
    build: .
    #environment:
    #  - "RDECK_URL=https:\\/\\/test\\.rundeck\\.u6k\\.me"
    #  - "RDECK_ADMIN_USER=admin"
    #  - "RDECK_ADMIN_PASS=pass"
    #  - "AWS_ACCESS_KEY_ID=xxx"
    #  - "AWS_SECRET_ACCESS_KEY=xxx"
    #  - "AWS_DEFAULT_REGION=us-east-1"
    #  - "AWS_S3_ENDPOINT=http://minio:9000"
    #  - "VIRTUAL_HOST=test.rundeck.u6k.me"
    #  - "VIRTUAL_PORT=4440"
    #  - "LETSENCRYPT_HOST=test.rundeck.u6k.me"
    #  - "LETSENCRYPT_EMAIL=u6k.apps@gmail.com"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "rundeck_projects:/opt/rundeck/projects/"
      - "rundeck_data:/opt/rundeck/server/data/"
      - "rundeck_logs:/opt/rundeck/var/logs/"
    ports:
      - "4440:4440"

volumes:
  rundeck_projects:
    driver: local
  rundeck_data:
    driver: local
  rundeck_logs:
    driver: local

#networks:
#  default:
#    external:
#      name: docker_default
