version: '3'

services:
  rundeck:
    build: .
    environment:
      - "RUNDECK_GRAILS_URL=https://xxx.ngrok.io"
      - "JAVA_TOOL_OPTIONS=-Xms1024M -Xmx1024M"
    volumes:
      - "rundeck_data:/home/rundeck/server/data"
      - "./realm.properties:/home/rundeck/server/config/realm.properties"
      - "/dev/null:/home/rundeck/etc/rundeckpro-license.key"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "4440:4440"

volumes:
  rundeck_data:
    driver: local
